### PR TITLE
Update MAINTAINERS.md

### PR DESCRIPTION
**Pull request by noobie3007**
Test benchmark workflow

### CODE REVIEW

**Comment by noobie3007** [comment]
{"run-benchmark-test": "id_9"}

**Comment by noobie3007** [comment]
{"run-benchmark-test": "id_9"}

**Comment by rishabh6788** [comment]
{"run-benchmark-test": "id_9"}

**Comment by rishabh6788** [comment]
{"run-benchmark-test": "id_9"}

**Pull request closed without merging**
